import React from "react";
import {
  Shield,
  UserCog,
  User,
  Building2,
  Users,
  UserPlus,
  Network,
  Briefcase,
  Settings,
  Home,
  FileText,
  Calendar,
  Clock,
  Bell,
  Mail,
  MessageSquare,
  FolderOpen,
  Database,
  BarChart3,
  PieChart,
  TrendingUp,
  Wallet,
  CreditCard,
  ShoppingCart,
  Package,
  Truck,
  Map,
  Globe,
  Phone,
  Video,
  ImageIcon,
  Camera,
  Mic,
  Music,
  Play,
  Heart,
  Star,
  Flag,
  Bookmark,
  Tag,
  Hash,
  AtSign,
  Link,
  Paperclip,
  Download,
  Upload,
  Share,
  Send,
  Printer,
  Clipboard,
  CheckSquare,
  ListTodo,
  Target,
  Award,
  Gift,
  Zap,
  ShieldIcon,
  Lock,
  Key,
  Fingerprint,
  Scan,
  Search,
  Filter,
  SlidersHorizontal,
  Layers,
  Grid,
  List,
  Table,
  Kanban,
  GitBranch,
  Code,
  Terminal,
  Bug,
  Wrench,
  Cog,
  HelpCircle,
  Info,
  AlertCircle,
  AlertTriangle,
  XCircle,
  CheckCircle,
  LayoutDashboard,
  Crown,
  UserCheck,
  Eye,
  FilePlus,
  FileEdit,
  FileX,
} from "lucide-react";
import { ActionType } from "@/lib/rbac";

export const roleIcons: Record<string, React.ReactNode> = {
  admin: <Shield className="h-5 w-5" />,
  hr: <UserCog className="h-5 w-5" />,
  "hr-specialist": <UserCheck className="h-5 w-5" />,
  "team-lead": <Crown className="h-5 w-5" />,
  employee: <User className="h-5 w-5" />,
};

export const iconMap: Record<
  string,
  React.ComponentType<{ className?: string }>
> = {
  LayoutDashboard,
  Building2,
  Users,
  UserPlus,
  Network,
  Briefcase,
  User,
  Settings,
  Home,
  FileText,
  Calendar,
  Clock,
  Bell,
  Mail,
  MessageSquare,
  FolderOpen,
  Database,
  BarChart3,
  PieChart,
  TrendingUp,
  Wallet,
  CreditCard,
  ShoppingCart,
  Package,
  Truck,
  Map,
  Globe,
  Phone,
  Video,
  ImageIcon,
  Camera,
  Mic,
  Music,
  Play,
  Heart,
  Star,
  Flag,
  Bookmark,
  Tag,
  Hash,
  AtSign,
  Link,
  Paperclip,
  Download,
  Upload,
  Share,
  Send,
  Printer,
  Clipboard,
  CheckSquare,
  ListTodo,
  Target,
  Award,
  Gift,
  Zap,
  Shield: ShieldIcon,
  Lock,
  Key,
  Fingerprint,
  Scan,
  Search,
  Filter,
  SlidersHorizontal,
  Layers,
  Grid,
  List,
  Table,
  Kanban,
  GitBranch,
  Code,
  Terminal,
  Bug,
  Wrench,
  Cog,
  HelpCircle,
  Info,
  AlertCircle,
  AlertTriangle,
  XCircle,
  CheckCircle,
};

export const iconOptions = [
  // Navigation & Layout
  { value: "LayoutDashboard", label: "Dashboard", category: "Navigation" },
  { value: "Home", label: "Home", category: "Navigation" },
  { value: "Grid", label: "Grid", category: "Navigation" },
  { value: "List", label: "List", category: "Navigation" },
  { value: "Table", label: "Table", category: "Navigation" },
  { value: "Kanban", label: "Kanban", category: "Navigation" },
  { value: "Layers", label: "Layers", category: "Navigation" },
  // People & Organization
  { value: "Users", label: "Users", category: "People" },
  { value: "User", label: "User", category: "People" },
  { value: "UserPlus", label: "User Plus", category: "People" },
  { value: "Building2", label: "Building", category: "People" },
  { value: "Network", label: "Network", category: "People" },
  { value: "Briefcase", label: "Briefcase", category: "People" },
  // Documents & Files
  { value: "FileText", label: "Document", category: "Documents" },
  { value: "FolderOpen", label: "Folder", category: "Documents" },
  { value: "Clipboard", label: "Clipboard", category: "Documents" },
  { value: "Paperclip", label: "Attachment", category: "Documents" },
  // Time & Calendar
  { value: "Calendar", label: "Calendar", category: "Time" },
  { value: "Clock", label: "Clock", category: "Time" },
  // Communication
  { value: "Bell", label: "Notifications", category: "Communication" },
  { value: "Mail", label: "Email", category: "Communication" },
  { value: "MessageSquare", label: "Messages", category: "Communication" },
  { value: "Phone", label: "Phone", category: "Communication" },
  { value: "Video", label: "Video", category: "Communication" },
  { value: "Send", label: "Send", category: "Communication" },
  // Data & Analytics
  { value: "Database", label: "Database", category: "Data" },
  { value: "BarChart3", label: "Bar Chart", category: "Data" },
  { value: "PieChart", label: "Pie Chart", category: "Data" },
  { value: "TrendingUp", label: "Trending", category: "Data" },
  { value: "Target", label: "Target", category: "Data" },
  // Finance
  { value: "Wallet", label: "Wallet", category: "Finance" },
  { value: "CreditCard", label: "Credit Card", category: "Finance" },
  { value: "ShoppingCart", label: "Cart", category: "Finance" },
  // Tasks & Actions
  { value: "CheckSquare", label: "Checkbox", category: "Tasks" },
  { value: "ListTodo", label: "Todo List", category: "Tasks" },
  { value: "Flag", label: "Flag", category: "Tasks" },
  { value: "Bookmark", label: "Bookmark", category: "Tasks" },
  { value: "Star", label: "Star", category: "Tasks" },
  // Security & Settings
  { value: "Settings", label: "Settings", category: "System" },
  { value: "Cog", label: "Cog", category: "System" },
  { value: "Shield", label: "Shield", category: "System" },
  { value: "Lock", label: "Lock", category: "System" },
  { value: "Key", label: "Key", category: "System" },
  { value: "Wrench", label: "Wrench", category: "System" },
  // Status
  { value: "CheckCircle", label: "Success", category: "Status" },
  { value: "AlertCircle", label: "Alert", category: "Status" },
  { value: "AlertTriangle", label: "Warning", category: "Status" },
  { value: "Info", label: "Info", category: "Status" },
  { value: "HelpCircle", label: "Help", category: "Status" },
  // Misc
  { value: "Globe", label: "Globe", category: "Misc" },
  { value: "Map", label: "Map", category: "Misc" },
  { value: "Package", label: "Package", category: "Misc" },
  { value: "Award", label: "Award", category: "Misc" },
  { value: "Gift", label: "Gift", category: "Misc" },
  { value: "Zap", label: "Zap", category: "Misc" },
  { value: "Heart", label: "Heart", category: "Misc" },
  { value: "Tag", label: "Tag", category: "Misc" },
  { value: "Search", label: "Search", category: "Misc" },
  { value: "Filter", label: "Filter", category: "Misc" },
];

export const actionIcons: Record<ActionType, React.ReactNode> = {
  view: <Eye className="h-3.5 w-3.5" />,
  create: <FilePlus className="h-3.5 w-3.5" />,
  edit: <FileEdit className="h-3.5 w-3.5" />,
  delete: <FileX className="h-3.5 w-3.5" />,
};

export const colorOptions = [
  { value: "bg-rose-500/20 text-rose-400", label: "Rose" },
  { value: "bg-sky-500/20 text-sky-400", label: "Sky" },
  { value: "bg-emerald-500/20 text-emerald-400", label: "Emerald" },
  { value: "bg-amber-500/20 text-amber-400", label: "Amber" },
  { value: "bg-violet-500/20 text-violet-400", label: "Violet" },
  { value: "bg-pink-500/20 text-pink-400", label: "Pink" },
  { value: "bg-cyan-500/20 text-cyan-400", label: "Cyan" },
  { value: "bg-orange-500/20 text-orange-400", label: "Orange" },
];
